eureka:
  client:
    enabled: false

spring:
  application:
    name: yesaladin-front
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:/test
    username: sa
    password:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB  
  redis:
    host: 133.186.151.141
    port: 6379
    password: "*N2vya7H@muDTwdNMR!"
    database: 26

yesaladin:
  gateway:
    base: https://api.yesaladin.shop
    coupon: https://api.yesaladin.shop/coupon
    auth: https://api.yesaladin.shop/auth
    shop: https://api.yesaladin.shop/shop
