eureka:
  client:
    enabled: false

spring:
  application:
    name: yesaladin-front
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:/test
    username: sa
    password:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB  
  redis:
    host: 133.186.151.141
    port: 6379
    password: "*N2vya7H@muDTwdNMR!"
    database: 26

yesaladin:
  gateway:
    base: https://api.yesaladin.shop
    coupon: https://api.yesaladin.shop/coupon

server:
  port: 8081

storage-token:
  auth-url: https://api-identity.infrastructure.cloud.toast.com/v2.0/tokens
  storage-url: https://api-storage.cloud.toast.com/v1
  tenant-id: fcb81f74e379456b8ca0e091d351a7af
  storage-account: AUTH_fcb81f74e379456b8ca0e091d351a7af
  container-name: yesaladinTest
  username: tidh1640@naver.com
  password: yesaladin
